### ISSUE TITLE
[BUG] html css transparent color problem

### ISSUE THREAD

**Issue by GoddenXD** [CCBlueX/LiquidBounce#5198]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

nextgen 0.4.1

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I want to make the frame HTML component in Nextgen transparent, so that I can see the image behind the frame component

In CSS style, 
```CSS
html, body {
  margin: 0;           
  padding: 0;          
  background: transparent;
}

canvas {
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  background: transparent;
}
```
The display effect will also be transparent, but it will be black in the game

example i hope:
![Q BG}8`@0A6{6APGOC( 9)P](https://github.com/user-attachments/assets/e827161d-590e-4123-8b01-158b0e06b8cd)

but the real situation in the game:
![U1(%QDNT04GCZIF78`PBY3K](https://github.com/user-attachments/assets/277e8248-c6b6-42b8-a0c5-e23d9d1610e3)

in browser:
![C8R~UX} JQUZ6R2IDCVV564](https://github.com/user-attachments/assets/33a1826c-f598-4c42-8225-f2c7ff642508)

### Steps to reproduce

-

### Client Log

```shell
-
```

### Screenshots

-
